version: '3.8'

services:

  # ---------- Messaging ----------
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6.0  #Bitnami is better than wurstmeister. more updates and dev friendly
    container_name: kafka
    restart: always
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  # ---------- Flink ----------
  flink-jobmanager:
    image: flink:1.17
    command: jobmanager
    volumes:
      - ./flink/libs:/opt/flink/lib
    ports: ["8081:8081"]
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-taskmanager:
    image: flink:1.17
    command: taskmanager
    volumes:
      - ./flink/libs:/opt/flink/lib
    depends_on: [flink-jobmanager]
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2

  # ---------- Storage ----------
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: network_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ---------- Data Ingestion ----------
  nifi:
    image: apache/nifi:2.5.0
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=8443
    depends_on:
      - kafka
      - postgres
    restart: unless-stopped
  # ---------- Mock Tower Simulator ----------
  # tower-simulator:
  #   build: ./tower-simulator
  #   container_name: tower-simulator
  #   restart: always
  #   environment:
  #     KAFKA_BROKER: kafka:9092
  #     TOPIC_NAME: cell-tower-metrics
  #   depends_on:
  #     - kafka
  # ---------- Monitoring ----------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "8889:8889"  # Prometheus scrapes here

volumes:
  grafana-storage:
  postgres_data:
  nifi_data:
